///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AfadDepremModel {
/*
{
  "rms": "0.27",
  "eventID": "484057",
  "location": "Ege Denizi - [29.56 km] Seferihisar (İzmir)",
  "latitude": "37.8376",
  "longitude": "26.7476",
  "depth": "8.82",
  "type": "Mw",
  "magnitude": "4.2",
  "country": "Türkiye",
  "province": "İzmir",
  "district": "Seferihisar",
  "neighborhood": null,
  "date": "2020-10-30T22:53:21.18",
  "isEventUpdate": false,
  "lastUpdateDate": null
} 
*/

  String? rms;
  String? eventID;
  String? location;
  String? latitude;
  String? longitude;
  String? depth;
  String? type;
  String? magnitude;
  String? country;
  String? province;
  String? district;
  String? neighborhood;
  String? date;
  bool? isEventUpdate;
  String? lastUpdateDate;

  AfadDepremModel({
    this.rms,
    this.eventID,
    this.location,
    this.latitude,
    this.longitude,
    this.depth,
    this.type,
    this.magnitude,
    this.country,
    this.province,
    this.district,
    this.neighborhood,
    this.date,
    this.isEventUpdate,
    this.lastUpdateDate,
  });
  AfadDepremModel.fromJson(Map<String, dynamic> json) {
    rms = json['rms']?.toString();
    eventID = json['eventID']?.toString();
    location = json['location']?.toString();
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
    depth = json['depth']?.toString();
    type = json['type']?.toString();
    magnitude = json['magnitude']?.toString();
    country = json['country']?.toString();
    province = json['province']?.toString();
    district = json['district']?.toString();
    neighborhood = json['neighborhood']?.toString();
    date = json['date']?.toString();
    isEventUpdate = json['isEventUpdate'];
    lastUpdateDate = json['lastUpdateDate']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['rms'] = rms;
    data['eventID'] = eventID;
    data['location'] = location;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['depth'] = depth;
    data['type'] = type;
    data['magnitude'] = magnitude;
    data['country'] = country;
    data['province'] = province;
    data['district'] = district;
    data['neighborhood'] = neighborhood;
    data['date'] = date;
    data['isEventUpdate'] = isEventUpdate;
    data['lastUpdateDate'] = lastUpdateDate;
    return data;
  }
}
