///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class KandilliDepremModelResult {
/*
{
  "mag": 4.3,
  "lng": 36.6138,
  "lat": 37.8438,
  "lokasyon": "CEVREPINAR-(KAHRAMANMARAS)",
  "depth": 5,
  "coordinates": [
    36.6138
  ],
  "title": "CEVREPINAR-(KAHRAMANMARAS)",
  "rev": null,
  "timestamp": 1675871397,
  "date_stamp": "2023-02-08",
  "date": "2023.02.08 18:49:57",
  "hash": "43179f88a8cd38bb1844f826234e9899",
  "hash2": "a400b804fbcc894ae3c150fb972c3b62"
} 
*/

  double? mag;
  double? lng;
  double? lat;
  String? lokasyon;
  int? depth;
  List<double?>? coordinates;
  String? title;
  String? rev;
  int? timestamp;
  String? dateStamp;
  String? date;
  String? hash;
  String? hash2;

  KandilliDepremModelResult({
    this.mag,
    this.lng,
    this.lat,
    this.lokasyon,
    this.depth,
    this.coordinates,
    this.title,
    this.rev,
    this.timestamp,
    this.dateStamp,
    this.date,
    this.hash,
    this.hash2,
  });
  KandilliDepremModelResult.fromJson(Map<String, dynamic> json) {
    mag = json['mag']?.toDouble();
    lng = json['lng']?.toDouble();
    lat = json['lat']?.toDouble();
    lokasyon = json['lokasyon']?.toString();
    depth = json['depth']?.toInt();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
    title = json['title']?.toString();
    rev = json['rev']?.toString();
    timestamp = json['timestamp']?.toInt();
    dateStamp = json['date_stamp']?.toString();
    date = json['date']?.toString();
    hash = json['hash']?.toString();
    hash2 = json['hash2']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['mag'] = mag;
    data['lng'] = lng;
    data['lat'] = lat;
    data['lokasyon'] = lokasyon;
    data['depth'] = depth;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    data['title'] = title;
    data['rev'] = rev;
    data['timestamp'] = timestamp;
    data['date_stamp'] = dateStamp;
    data['date'] = date;
    data['hash'] = hash;
    data['hash2'] = hash2;
    return data;
  }
}

class KandilliDepremModel {
/*
{
  "status": true,
  "tryed": 0,
  "serverloadms": 252,
  "desc": "Gerçekten amacına uygun kullanın, Lütfen iletişimden çekinmeyin: info@orhanaydogdu.com.tr",
  "result": [
    {
      "mag": 4.3,
      "lng": 36.6138,
      "lat": 37.8438,
      "lokasyon": "CEVREPINAR-(KAHRAMANMARAS)",
      "depth": 5,
      "coordinates": [
        36.6138
      ],
      "title": "CEVREPINAR-(KAHRAMANMARAS)",
      "rev": null,
      "timestamp": 1675871397,
      "date_stamp": "2023-02-08",
      "date": "2023.02.08 18:49:57",
      "hash": "43179f88a8cd38bb1844f826234e9899",
      "hash2": "a400b804fbcc894ae3c150fb972c3b62"
    }
  ]
} 
*/

  bool? status;
  int? tryed;
  int? serverloadms;
  String? desc;
  List<KandilliDepremModelResult?>? result;

  KandilliDepremModel({
    this.status,
    this.tryed,
    this.serverloadms,
    this.desc,
    this.result,
  });
  KandilliDepremModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    tryed = json['tryed']?.toInt();
    serverloadms = json['serverloadms']?.toInt();
    desc = json['desc']?.toString();
  if (json['result'] != null) {
  final v = json['result'];
  final arr0 = <KandilliDepremModelResult>[];
  v.forEach((v) {
  arr0.add(KandilliDepremModelResult.fromJson(v));
  });
    result = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['tryed'] = tryed;
    data['serverloadms'] = serverloadms;
    data['desc'] = desc;
    if (result != null) {
      final v = result;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['result'] = arr0;
    }
    return data;
  }
}
